import { useEffect, useState } from 'react'
import { Code, Download, FileCode, Check } from 'lucide-react'
import Card from '../components/ui/Card.jsx'
import Spinner from '../components/ui/Spinner.jsx'
import { datasetService } from '../services/datasetService.js'

export default function Pipeline() {
  const [data, setData] = useState(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    let active = true
    datasetService.getPipelineCode().then((res) => {
      if (active) setData(res)
    })
    return () => {
      active = false
    }
  }, [])

  const handleDownload = () => {
    if (!data?.code) return
    const blob = new Blob([data.code], { type: 'text/x-python' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'pipeline.py'
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleCopy = () => {
    if (!data?.code) return
    navigator.clipboard.writeText(data.code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  if (!data) return <Spinner label="Generating ML pipeline script..." />

  return (
    <div className="space-y-6">
      <p className="text-sm text-slate-500">
        Pipeline Export <span className="mx-1 text-slate-700">&rsaquo;</span>{' '}
        <span className="text-slate-300">Code Generator</span>
      </p>

      <div className="flex items-center justify-between gap-3">
        <div>
          <h2 className="text-sm font-medium text-slate-400">Scikit-Learn ML Pipeline</h2>
          <p className="text-xs text-slate-500 mt-0.5">Fully structured training pipeline generated by the backend modules.</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopy}
            className="btn-secondary py-2 px-3 text-xs"
          >
            {copied ? <Check size={14} className="text-emerald-500" /> : <FileCode size={14} />}
            {copied ? 'Copied!' : 'Copy Code'}
          </button>
          <button
            type="button"
            onClick={handleDownload}
            className="btn-primary py-2 px-3 text-xs"
          >
            <Download size={14} />
            Download pipeline.py
          </button>
        </div>
      </div>

      <Card className="p-0 overflow-hidden">
        <div className="bg-[#1c1b1a] p-4 text-xs font-mono text-slate-300 overflow-x-auto select-all max-h-[60vh]">
          <pre>{data.code}</pre>
        </div>
      </Card>
    </div>
  )
}
