"""
pipeline_generator.py

Generates a complete standalone sklearn pipeline script
based on the preprocessing decisions and best model selected
by ML Assistant.
"""

from textwrap import dedent

from sklearn.model_selection import train_test_split

MODEL_IMPORTS = {
    "Linear Regression":
        ("from sklearn.linear_model import LinearRegression",
         "LinearRegression()"),

    "Logistic Regression":
        ("from sklearn.linear_model import LogisticRegression",
         "LogisticRegression(max_iter=1000)"),

    "Decision Tree":
        ("from sklearn.tree import DecisionTreeClassifier",
         "DecisionTreeClassifier(random_state=42)"),

    "Random Forest":
        ("from sklearn.ensemble import RandomForestClassifier",
         "RandomForestClassifier(random_state=42)"),

    "Random Forest Regressor":
        ("from sklearn.ensemble import RandomForestRegressor",
         "RandomForestRegressor(random_state=42)"),

    "Gradient Boosting":
        ("from sklearn.ensemble import GradientBoostingClassifier",
         "GradientBoostingClassifier(random_state=42)"),

    "Gradient Boosting Regressor":
        ("from sklearn.ensemble import GradientBoostingRegressor",
         "GradientBoostingRegressor(random_state=42)"),

    "XGBoost":
        ("from xgboost import XGBClassifier",
         "XGBClassifier(eval_metric='logloss', random_state=42)"),

    "XGBoost Regressor":
        ("from xgboost import XGBRegressor",
         "XGBRegressor(random_state=42)"),

    "SVM":
        ("from sklearn.svm import SVC",
         "SVC(probability=True)"),

    "SVR":
        ("from sklearn.svm import SVR",
         "SVR()"),

    "KNN":
        ("from sklearn.neighbors import KNeighborsClassifier",
         "KNeighborsClassifier()"),

    "KNN Regressor":
        ("from sklearn.neighbors import KNeighborsRegressor",
         "KNeighborsRegressor()"),

    "Naive Bayes":
        ("from sklearn.naive_bayes import GaussianNB",
         "GaussianNB()"),
}


SCALERS = {
    "StandardScaler":
        "StandardScaler()",

    "MinMaxScaler":
        "MinMaxScaler()",

    "RobustScaler":
        "RobustScaler()",

    None:
        "passthrough",

    "":
        "passthrough"
}


IMPUTERS = {
    "mean": "mean",
    "median": "median",
    "most_frequent": "most_frequent",
    "constant": "constant"
}


ENCODERS = {
    "OneHotEncoder":
        "OneHotEncoder(handle_unknown='ignore')",

    "OrdinalEncoder":
        "OrdinalEncoder()",

    None:
        "OneHotEncoder(handle_unknown='ignore')",

    "":
        "OneHotEncoder(handle_unknown='ignore')"
}


def _python_list(values):
    return "[" + ", ".join(f'"{v}"' for v in values) + "]"


def generate_pipeline_code(
        numerical_features,
        categorical_features,
        target_column,
        model_name,
        scaler="StandardScaler",
        numerical_imputer="median",
        categorical_imputer="most_frequent",
        encoder="OneHotEncoder"
):
    """
    Returns a complete python script as string.
    """

    model_import, model_constructor = MODEL_IMPORTS.get(
        model_name,
        (
            "from sklearn.ensemble import RandomForestClassifier",
            "RandomForestClassifier(random_state=42)"
        )
    )

    scaler_constructor = SCALERS.get(
        scaler,
        "StandardScaler()"
    )

    encoder_constructor = ENCODERS.get(
        encoder,
        "OneHotEncoder(handle_unknown='ignore')"
    )

    num_strategy = IMPUTERS.get(
        numerical_imputer,
        "median"
    )

    cat_strategy = IMPUTERS.get(
        categorical_imputer,
        "most_frequent"
    )

    scaler_imports = dedent("""
        from sklearn.preprocessing import (
            StandardScaler,
            MinMaxScaler,
            RobustScaler,
            OneHotEncoder,
            OrdinalEncoder
        )
    """)

    code = f'''
"""
==========================================
Generated by ML Assistant
==========================================
"""

import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

{scaler_imports}

{model_import}


# --------------------------
# Load Dataset
# --------------------------

df = pd.read_csv("your_dataset.csv")


TARGET = "{target_column}"


X = df.drop(columns=[TARGET])
y = df[TARGET]


numeric_features = {_python_list(numerical_features)}

categorical_features = {_python_list(categorical_features)}


numeric_transformer = Pipeline(

    steps=[

        ("imputer",
         SimpleImputer(strategy="{num_strategy}")),

        ("scaler",
         {scaler_constructor})
    ]

)


categorical_transformer = Pipeline(

    steps=[

        ("imputer",
         SimpleImputer(strategy="{cat_strategy}")),

        ("encoder",
         {encoder_constructor})
    ]

)


preprocessor = ColumnTransformer(

    transformers=[

        (
            "num",
            numeric_transformer,
            numeric_features
        ),

        (
            "cat",
            categorical_transformer,
            categorical_features
        )

    ]

)


pipeline = Pipeline(

    steps=[

        (
            "preprocessor",
            preprocessor
        ),

        (
            "model",
            {model_constructor}
        )

    ]

)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

pipeline.fit(X_train, y_train)

print("Pipeline trained successfully.")

# Save if needed

# import joblib
# joblib.dump(pipeline, "pipeline.pkl")
'''

    return dedent(code)